### ISSUE TITLE
Add gitignore

### ISSUE THREAD

**Issue by anaoprea** [anaoprea/iDibo#2]
a) Read about .gitignore does, there is a comment in one of the files that you added.
b) Create a new branch (call it feature/adding_gitignore for example)
c) Go to https://www.gitignore.io/
d) Generate a file for PyCharm, Python and save it as .gitignore under the project root (iDibo/.gitignore for example).
e) Create a pull request :)

**Comment by OluyemisiAkin** [comment]
I jsut want to confirm that you actually want the .gitignore file to be added in the feature brach, because tat is what i did.

**Comment by anaoprea** [comment]
I would like you to create a new branch, that I will merge.

A branch should represent only one feature, in our current case the initial
branch with the tutorials will always be available for you to add stuff,
but should never be merged in the main project.

I have time tomorrow between 11-16 EET  (UTC+2), please let me know if that
works for you. I think a 30min-1h sync should be enough,  but also 10 min
would work if you don't have the time and we'll talk through emails and the
Google docs :)

Have a great evening,
Ana

**Comment by OluyemisiAkin** [comment]
I'm currently having issues pushing the updaetes i made: that is the
.gitignore i created and also the doctest i implemented in one of the test
tutorials, i keep getting error of could not read from remote repository
and sometime access error I've tried to search for help, but no headway.
Any hints?

On Wed, Dec 17, 2014 at 11:05 PM, Ana Oprea notifications@github.com
wrote:

> I would like you to create a new branch, that I will merge.
> 
> A branch should represent only one feature, in our current case the initial
> branch with the tutorials will always be available for you to add stuff,
> but should never be merged in the main project.
> 
> I have time tomorrow between 11-16 EET (UTC+2), please let me know if that
> works for you. I think a 30min-1h sync should be enough, but also 10 min
> would work if you don't have the time and we'll talk through emails and the
> Google docs :)
> 
> Have a great evening,
> Ana
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/anaoprea/iDibo/issues/2#issuecomment-67403462.

## 

We are what we repeatedly do. Excellence, therefore, is not an act but a
habit.!!!!

Best Regards,
Oladayo
+2348069385406

**Comment by anaoprea** [comment]
I don't know .. make sure:
1. You are on the right branch: git brauch (it should be the one with the
tutorial)
2 git pull
3 git add the fils to be committed
4 git commit  -m "msg"
5  git push

You should be able to do all those from pyxharm or cli

Please give me the exact error if it doesn't work out I will help you debug
tomorrow :)

**Comment by OluyemisiAkin** [comment]
I've pushed the updates and i've sent a pull request. I hope you've seen
them. The issue  had was i was trying to push directly to your repo which i
dont have access instead of pushing to my origin and sending a pull request
to you. I don't fully understand the second issue raised here, please
expatiate in case its not covered in what i've done.
Thanks

On Wed, Dec 17, 2014 at 11:40 PM, Ana Oprea notifications@github.com
wrote:

> I don't know .. make sure:
> 1. You are on the right branch: git brauch (it should be the one with the
> tutorial)
> 2 git pull
> 3 git add the fils to be committed
> 4 git commit -m "msg"
> 5 git push
> 
> You should be able to do all those from pyxharm or cli
> 
> Please give me the exact error if it doesn't work out I will help you
> debug
> tomorrow :)
> On Dec 18, 2014 12:32 AM, "Dasatt" notifications@github.com wrote:
> 
> > I'm currently having issues pushing the updaetes i made: that is the
> > .gitignore i created and also the doctest i implemented in one of the
> > test
> > tutorials, i keep getting error of could not read from remote repository
> > and sometime access error I've tried to search for help, but no headway.
> > Any hints?
> > 
> > On Wed, Dec 17, 2014 at 11:05 PM, Ana Oprea notifications@github.com
> > wrote:
> > 
> > > I would like you to create a new branch, that I will merge.
> > > 
> > > A branch should represent only one feature, in our current case the
> > > initial
> > > branch with the tutorials will always be available for you to add
> > > stuff,
> > > but should never be merged in the main project.
> > > 
> > > I have time tomorrow between 11-16 EET (UTC+2), please let me know if
> > > that
> > > works for you. I think a 30min-1h sync should be enough, but also 10
> > > min
> > > would work if you don't have the time and we'll talk through emails
> > > and
> > > the
> > > Google docs :)
> > > 
> > > Have a great evening,
> > > Ana
> > > 
> > > ## 
> > > 
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/anaoprea/iDibo/issues/2#issuecomment-67403462.
> > 
> > ## 
> > 
> > We are what we repeatedly do. Excellence, therefore, is not an act but a
> > habit.!!!!
> > 
> > Best Regards,
> > Oladayo
> > +2348069385406
> > 
> > ## 
> > 
> > Reply to this email directly or view it on GitHub
> > https://github.com/anaoprea/iDibo/issues/2#issuecomment-67408550.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/anaoprea/iDibo/issues/2#issuecomment-67410237.

## 

We are what we repeatedly do. Excellence, therefore, is not an act but a
habit.!!!!

Best Regards,
Oladayo
+2348069385406

**Comment by anaoprea** [comment]
Hi Yemisi,

One of the reasons why you should not put directly to the master is to
enable reviews: when there is a large team working on a project, each
member will have a task to solve and, at least one other person, will have
a look at the implementation and bring suggestions for improvements. This
way, on a branch, there can be multiple changes that can later be
cherry-picked [1].

For example, in this branch, you have initially added the tutorial
exercises and deleted them at the end - these operations are in the history
of the branch, so, if I merge it to master, this redundant operation will
be there. However, if I cherry-pick only the gitignore and the readme in a
different branch that I merge, then the master will be in a more "clean"
state.

Please let me know if you need more info regarding this :)

[1]
http://stackoverflow.com/questions/449541/how-do-you-merge-selective-files-with-git-merge

**Comment by OluyemisiAkin** [comment]
I think I'm getting a better picture of the whole operation gradually. But
so far i've not tampered with the master i guess.

On Sat, Dec 20, 2014 at 10:44 AM, Ana Oprea notifications@github.com
wrote:

> Hi Yemisi,
> 
> One of the reasons why you should not put directly to the master is to
> enable reviews: when there is a large team working on a project, each
> member will have a task to solve and, at least one other person, will have
> a look at the implementation and bring suggestions for improvements. This
> way, on a branch, there can be multiple changes that can later be
> cherry-picked [1].
> 
> For example, in this branch, you have initially added the tutorial
> exercises and deleted them at the end - these operations are in the history
> of the branch, so, if I merge it to master, this redundant operation will
> be there. However, if I cherry-pick only the gitignore and the readme in a
> different branch that I merge, then the master will be in a more "clean"
> state.
> 
> Please let me know if you need more info regarding this :)
> 
> [1]
> 
> http://stackoverflow.com/questions/449541/how-do-you-merge-selective-files-with-git-merge
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/anaoprea/iDibo/issues/2#issuecomment-67730664.

## 

We are what we repeatedly do. Excellence, therefore, is not an act but a
habit.!!!!

Best Regards,
Oladayo
+2348069385406
